### ISSUE TITLE
devtools::load_all() doesn't work

### ISSUE THREAD

**Issue by krlmlr** [jimhester/withr#34]
Fails with hadley/devtools@89e7bfd1d5e, succeeds with CRAN devtools 1.9.1.

```
Loading withr
Error in imp_env$system.file <- shim_system.file : 
  cannot add bindings to a locked environment
2: insert_imports_shims(pkg)
1: devtools::load_all(".")
```

**Comment by jimhester** [comment]
I guess this is caused by devel devtools Importing withr? The error message doesn't make much sense to me though, why is `imp_env` locked in this case...

**Comment by jimhester** [comment]
Ok so the real issue is that because `devtools::load_all()` calls a number of withr functions (i.e. https://github.com/hadley/devtools/blob/be08bbfc80291a7840eb092fa31b0cb6d1905587/R/load-code.r#L26) the withr namespace is automatically loaded by R.

When R loads a namespace it is locked (unlike when devtools loads it), so because of this we get the above error.

Not sure what we can do to fix this however...

**Comment by krlmlr** [comment]
I guess we can use "Build & Reload" and `roxygen2::roxygenize()` instead. Just have to keep that in mind. I'll change the settings in the `.Rproj` file.
